/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_IO_Abstraction_SWC_.c
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "string.h"
#include "Rte_IO_Abstraction_SWC.h"


Rte_DE_Door_State_t Get_Door_State_Get_Sensor_State_Sender_Current_State;


const Rte_CDS_IO_Abstraction_SWC Rte_Instance_IO_Abstraction_SWC = {
&Get_Door_State_Get_Sensor_State_Sender_Current_State
};

const Rte_CDS_IO_Abstraction_SWC * const Rte_Inst_IO_Abstraction_SWC = &Rte_Instance_IO_Abstraction_SWC;




void Rte_IWrite_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State (Door_State_t Current_State)
{
	(Rte_Inst_IO_Abstraction_SWC)->Get_Door_State_Get_Sensor_State_Sender_Current_State->value = Current_State;
}
Door_State_t* Rte_IWriteRef_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void)
{
	return &(Rte_Inst_IO_Abstraction_SWC)->Get_Door_State_Get_Sensor_State_Sender_Current_State->value;
}
