/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef unsigned char LED_State_t;
typedef unsigned char Door_State_t;


/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	Door_State_t value;
} Rte_DE_Door_State_t;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: IO_Abstraction_SWC 
 *********************************************************************/
typedef struct Rte_CDS_IO_Abstraction_SWC
{
	/* Data Handles section*/
	Rte_DE_Door_State_t *Get_Door_State_Get_Sensor_State_Sender_Current_State;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_IO_Abstraction_SWC;

/*********************************************************************
 * component data structure for SWC: Door_Lock_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Door_Lock_SWC
{
	/* Data Handles section*/
	Rte_DE_Door_State_t *Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_Door_Lock_SWC;

/*********************************************************************
 * component data structure for SWC: Composite_Application_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Composite_Application_SWC
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_Composite_Application_SWC;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
