/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_IO_Abstraction_SWC.h
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#ifndef RTE_IO_ABSTRACTION_SWC_H
#define RTE_IO_ABSTRACTION_SWC_H

#include "Rte_IO_Abstraction_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_IO_Abstraction_SWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_IO_Abstraction_SWC * const Rte_Inst_IO_Abstraction_SWC;

/************************ application errors *************************/

#define RTE_E_Client_Server_Interface_Control_LED_E_OK ((Std_ReturnType)0)
#define RTE_E_Client_Server_Interface_Control_LED_E_NOT_OK ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		Get_Sensor_State_Sender
 * Interface:	Sender_Receiver_Interface_Door_Sensor
 * DataElement:	Current_State
 * Runnable:	Get_Door_State
 *****************************************************/
extern void Rte_IWrite_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State (Door_State_t Current_State);
#ifndef IN_RTE_C
#define Rte_IWrite_Get_Door_State_Get_Sensor_State_Sender_Current_State(RTEData) \
	Rte_IWrite_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(RTEData)
#endif
extern Door_State_t* Rte_IWriteRef_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_Get_Door_State_Get_Sensor_State_Sender_Current_State() \
	Rte_IWriteRef_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State()
#endif

/*****************************************************
 * Port: 		Control_Led_State_Server
 * Interface:	Client_Server_Interface_Control_LED
 * Operation:	Set_LED_State
 *****************************************************/
extern Std_ReturnType Update_LED_State_Runnable(LED_State_t LED_State) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	Get_Door_State
 * Period:		0.01
 *****************************************************/
extern void Get_Door_State_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_IO_ABSTRACTION_SWC_H */
