/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Door_Lock_SWC_.c
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "string.h"
#include "Rte_Door_Lock_SWC.h"


Rte_DE_Door_State_t Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State;


const Rte_CDS_Door_Lock_SWC Rte_Instance_Door_Lock_SWC = {
&Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State
};

const Rte_CDS_Door_Lock_SWC * const Rte_Inst_Door_Lock_SWC = &Rte_Instance_Door_Lock_SWC;


Std_ReturnType Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Buffer_retcode = RTE_E_OK;

FunctionPtr_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate = 0;

Door_State_t Rte_IRead_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State (void)
{
	return (Rte_Inst_Door_Lock_SWC)->Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State->value;
}
Std_ReturnType Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State (LED_State_t LED_State)
{
	Std_ReturnType __result = Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Buffer_retcode;
	if ( Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate != 0 ) {
		__result = Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate(LED_State);
	}
	return __result;
}
