/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Door_Lock_SWC_Type.h
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#ifndef RTE_DOOR_LOCK_SWC_TYPE_H
#define RTE_DOOR_LOCK_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define Door_State_t_LowerLimit  (0U)
#define Door_State_t_UpperLimit (255U)
#define LED_State_t_LowerLimit  (0U)
#define LED_State_t_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOOR_LOCK_SWC_TYPE_H */
