/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Door_Lock_SWC.h
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "Rte_Door_Lock_SWC.h"	

#ifndef ARUNIT_DOOR_LOCK_SWC_H
#define ARUNIT_DOOR_LOCK_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_Set_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate(FunctionPtr_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State );
DECLSPEC_EXPORT void ARUnit_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_ReturnCode(Std_ReturnType returnCode);

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(Door_State_t Current_State);
DECLSPEC_EXPORT Door_State_t ARUnit_IRead_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(void);
DECLSPEC_EXPORT Door_State_t* ARUnit_IWriteRef_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_Door_Lock_SWC_Door_Lock_Logic_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_DOOR_LOCK_SWC_H */
