/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_IO_Abstraction_SWC.h
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "Rte_IO_Abstraction_SWC.h"	

#ifndef ARUNIT_IO_ABSTRACTION_SWC_H
#define ARUNIT_IO_ABSTRACTION_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(Door_State_t Current_State);
DECLSPEC_EXPORT Door_State_t ARUnit_IRead_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void);
DECLSPEC_EXPORT Door_State_t* ARUnit_IWriteRef_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_IO_Abstraction_SWC_Update_LED_State_Runnable(LED_State_t LED_State);

DECLSPEC_EXPORT void ARUnit_Trigger_IO_Abstraction_SWC_Get_Door_State_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_IO_ABSTRACTION_SWC_H */
