/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_Door_Lock_SWC_.c
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_Door_Lock_SWC.h"


extern const Rte_CDS_Door_Lock_SWC Rte_Instance_Door_Lock_SWC;
extern const Rte_CDS_Door_Lock_SWC * const Rte_Inst_Door_Lock_SWC;


extern Std_ReturnType Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Buffer_retcode;

extern FunctionPtr_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(Door_State_t Current_State)
{
	(Rte_Inst_Door_Lock_SWC)->Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State->value = Current_State;
}
DECLSPEC_EXPORT Door_State_t* ARUnit_IWriteRef_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(void)
{
	return &(Rte_Inst_Door_Lock_SWC)->Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State->value;
}
DECLSPEC_EXPORT Door_State_t ARUnit_IRead_Door_Lock_SWC_Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State(void)
{
	return (Rte_Inst_Door_Lock_SWC)->Door_Lock_Logic_Get_Sensor_State_Receiver_Current_State->value;
}
DECLSPEC_EXPORT void ARUnit_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_ReturnCode(Std_ReturnType returnCode)
{
	Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate(FunctionPtr_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State  delegate)
{
	Rte_Call_Door_Lock_SWC_Control_Led_State_Client_Set_LED_State_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_Door_Lock_SWC_Door_Lock_Logic_Runnable(void)
{
	Door_Lock_Logic_Runnable();
}
