/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_IO_Abstraction_SWC_.c
 * Generated on: Tue Apr 15 6:42:33 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_IO_Abstraction_SWC.h"


extern const Rte_CDS_IO_Abstraction_SWC Rte_Instance_IO_Abstraction_SWC;
extern const Rte_CDS_IO_Abstraction_SWC * const Rte_Inst_IO_Abstraction_SWC;




DECLSPEC_EXPORT void ARUnit_IWrite_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(Door_State_t Current_State)
{
		(Rte_Inst_IO_Abstraction_SWC)->Get_Door_State_Get_Sensor_State_Sender_Current_State->value = Current_State;
}
DECLSPEC_EXPORT Door_State_t* ARUnit_IWriteRef_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void)
{
	return &(Rte_Inst_IO_Abstraction_SWC)->Get_Door_State_Get_Sensor_State_Sender_Current_State->value;
}
DECLSPEC_EXPORT Door_State_t ARUnit_IRead_IO_Abstraction_SWC_Get_Door_State_Get_Sensor_State_Sender_Current_State(void)
{
	return (Rte_Inst_IO_Abstraction_SWC)->Get_Door_State_Get_Sensor_State_Sender_Current_State->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_IO_Abstraction_SWC_Update_LED_State_Runnable(LED_State_t LED_State)
{
	return Update_LED_State_Runnable(LED_State);
}


DECLSPEC_EXPORT void ARUnit_Trigger_IO_Abstraction_SWC_Get_Door_State_Runnable(void)
{
	Get_Door_State_Runnable();
}
